---
- name: network device backup to git
#  hosts: routers
#  hosts: rtr3
  hosts: routers
  gather_facts: false
  vars:
    backup_dir: "{{ playbook_dir }}/Backups"
    backup_file: "{{ backup_dir }}/{{ inventory_hostname }}"
    backup_repo: git@github.com:beasleymd/Backups
    git_name: Git Backup
    git_email: beasleymd@yahoo.com
  
  tasks:

  - import_role:
      name: network_backup_git
